package trycatch_in;

public class TestRuntimeException1 {
	public void foo() {
		Class clazz= null;
		
		/*[*/clazz.getConstructors();/*]*/
	}
}
